pm uninstall --user 0 cn.wps.moffice_eng
pm uninstall --user 0 cn.wps.xiaomi.abroad.lite
pm uninstall --user 0 com.alibaba.aliexpresshd
pm uninstall --user 0 com.amazon.appmanager
pm uninstall --user 0 com.amazon.fv
pm uninstall --user 0 com.amazon.kindle
pm uninstall --user 0 com.amazon.mp3
pm uninstall --user 0 com.amazon.mshop.android
pm uninstall --user 0 com.amazon.mshop.android.shopping
pm uninstall --user 0 com.amazon.venezia
pm uninstall --user 0 com.android.providers.downloads.ui
pm uninstall --user 0 com.audible.application
pm uninstall --user 0 com.bitdefender.security
pm uninstall --user 0 com.block.juggle
pm uninstall --user 0 com.block.puzzle.game.hippo.mi
pm uninstall --user 0 com.blurb.checkout
pm uninstall --user 0 com.booking
pm uninstall --user 0 com.cnn.mobile.android.phone.edgepanel
pm uninstall --user 0 com.crazy.juicer.xm
pm uninstall --user 0 com.duokan.phone.remotecontroller
pm uninstall --user 0 com.einnovation.temu
pm uninstall --user 0 com.enhance.gameservice
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.katana
pm uninstall --user 0 com.facebook.orca
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.flipboard.app
pm uninstall --user 0 com.flipboard.boxer.app
pm uninstall --user 0 com.fugo.wow
pm uninstall --user 0 com.funtomic.matchmasters
pm uninstall --user 0 com.gameduell.tarot
pm uninstall --user 0 com.google.android.apps.books
pm uninstall --user 0 com.google.android.apps.docs
pm uninstall --user 0 com.google.android.apps.magazines
pm uninstall --user 0 com.google.android.apps.plus
pm uninstall --user 0 com.google.android.apps.subscriptions.red
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.google.android.apps.youtube.music
pm uninstall --user 0 com.google.android.music
pm uninstall --user 0 com.google.android.talk
pm uninstall --user 0 com.google.android.videos
pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
pm uninstall --user 0 com.imdb.mobile
pm uninstall --user 0 com.infraware.polarisoffice5
pm uninstall --user 0 com.jewelsblast.ivygames.adventure.free
pm uninstall --user 0 com.lemon.lvoverseas
pm uninstall --user 0 com.linkedin.android
pm uninstall --user 0 com.mi.global.pocobbs
pm uninstall --user 0 com.mi.global.pocostore
pm uninstall --user 0 com.mi.globalbrowser
pm uninstall --user 0 com.micredit.in
pm uninstall --user 0 com.microsoft.office.excel
pm uninstall --user 0 com.microsoft.office.officehubrow
pm uninstall --user 0 com.microsoft.office.outlook
pm uninstall --user 0 com.microsoft.office.powerpoint
pm uninstall --user 0 com.microsoft.office.word
pm uninstall --user 0 com.microsoft.skydrive
pm uninstall --user 0 com.miui.analytics
pm uninstall --user 0 com.miui.audioeffect
pm uninstall --user 0 com.miui.audiomonitor
pm uninstall --user 0 com.miui.carlink
pm uninstall --user 0 com.miui.compass
pm uninstall --user 0 com.miui.daemon
pm uninstall --user 0 com.miui.extraphoto
pm uninstall --user 0 com.miui.hybrid
pm uninstall --user 0 com.miui.hybrid.accessory
pm uninstall --user 0 com.miui.micloudsync
pm uninstall --user 0 com.miui.mishare.connectivity
pm uninstall --user 0 com.miui.misightservice
pm uninstall --user 0 com.miui.misound
pm uninstall --user 0 com.miui.msa.global
pm uninstall --user 0 com.miui.notes
pm uninstall --user 0 com.miui.notification
pm uninstall --user 0 com.miui.personalassistant
pm uninstall --user 0 com.miui.player
pm uninstall --user 0 com.miui.systemadsolution
pm uninstall --user 0 com.miui.touchassistant
pm uninstall --user 0 com.miui.translation.kingsoft
pm uninstall --user 0 com.miui.translation.xmcloud
pm uninstall --user 0 com.miui.translation.youdao
pm uninstall --user 0 com.miui.translationservice
pm uninstall --user 0 com.miui.userguide
pm uninstall --user 0 com.miui.videoplayer
pm uninstall --user 0 com.miui.voiceassist
pm uninstall --user 0 com.miui.voiceassistoverlay
pm uninstall --user 0 com.miui.voicetrigger
pm uninstall --user 0 com.miui.weather2
pm uninstall --user 0 com.miui.yellowpage
pm uninstall --user 0 com.moomoo.trade
pm uninstall --user 0 com.mygalaxy
pm uninstall --user 0 com.netflix.mediaclient
pm uninstall --user 0 com.netflix.partner.activation
pm uninstall --user 0 com.nf.snake
pm uninstall --user 0 com.oakever.tiletrip
pm uninstall --user 0 com.opera.browser
pm uninstall --user 0 com.opera.max.oem
pm uninstall --user 0 com.opera.preinstall
pm uninstall --user 0 com.plarium.raidlegends
pm uninstall --user 0 com.sec.android.app.withtv
pm uninstall --user 0 com.singtel.mysingtel
pm uninstall --user 0 com.skype.raider
pm uninstall --user 0 com.sohu.inputmethod.sogou.xiaomi
pm uninstall --user 0 com.soulcompany.bubbleshooter.relaxing
pm uninstall --user 0 com.spotify.music
pm uninstall --user 0 com.sukhavati.gotoplaying.bubble.bubbleshooter.mint
pm uninstall --user 0 com.touchtype.swiftkey
pm uninstall --user 0 com.tripadvisor.tripadvisor
pm uninstall --user 0 com.tripledot.solitaire
pm uninstall --user 0 com.vitastudio.mahjong
pm uninstall --user 0 com.vlingo.midas
pm uninstall --user 0 com.xiaomi.discover
pm uninstall --user 0 com.xiaomi.midrop
pm uninstall --user 0 com.xiaomi.mipicks
pm uninstall --user 0 com.xiaomi.mirecycle
pm uninstall --user 0 com.xiaomi.payment
pm uninstall --user 0 com.xiaomi.simactivate.service
pm uninstall --user 0 com.xiaomi.ugd
pm uninstall --user 0 com.zhiliaoapp.musically
pm uninstall --user 0 de.autodoc.gmbh
pm uninstall --user 0 net.wooga.junes_journey_hidden_object_mystery_game
